-- ============================================================
-- GMA: invented synopses for the 45 films with no REPASO text
-- Run AFTER migration.sql (or append to it)
-- ============================================================

UPDATE peliculas SET synopsis='En una espera interminable, varios personajes revelan quiénes son cuando el tiempo se detiene. Una reflexión animada sobre la paciencia, la identidad y lo que decidimos hacer mientras el mundo no nos necesita.' WHERE slug='a-cada-cual-su-espera';
UPDATE peliculas SET synopsis='Un repaso nostálgico y animado del mundo tal como era en el año previo a la pandemia — cuando lo cotidiano aún no era extraordinario y nadie guardaba nada por si acaso. Un documento de lo que perdimos sin saberlo.' WHERE slug='ano-1-antes-de-covid';
UPDATE peliculas SET synopsis='En menos de treinta segundos, una pérdida momentánea de visión desencadena una cascada de percepciones que el ojo no podría haber captado. Segunda entrega de la exploración de Caivano sobre lo que revela la oscuridad.' WHERE slug='ceguera-temporal-2';
UPDATE peliculas SET synopsis='Una criatura ejerce un control absoluto sobre la mente de otra en un juego de dominación que borra los límites entre voluntad y obediencia. Un corto que explora el poder como adicción y la identidad como territorio conquistable.' WHERE slug='control-mental';
UPDATE peliculas SET synopsis='El cuco emerge de las sombras familiares — debajo de la cama, dentro del armario, en el silencio de las tres de la mañana. Un corto que recupera el miedo ancestral de la infancia y lo convierte en algo que ningún adulto puede ignorar.' WHERE slug='cuco';
UPDATE peliculas SET synopsis='Una exploración audiovisual de la línea curva como unidad mínima del movimiento, la vida y la forma. Un corto que encuentra en la geometría más simple una complejidad infinita.' WHERE slug='curvilinea';
UPDATE peliculas SET synopsis='Dos fuerzas opuestas navegan un universo donde cada decisión carga el peso de su contraria. Un corto de cuatro minutos que explora la dualidad como condición irrenunciable de la existencia.' WHERE slug='dualidad';
UPDATE peliculas SET synopsis='Las películas abandonan la pantalla y el cine se convierte en algo más que una proyección — en una entidad con voluntad propia. Un cortometraje metafílmico que cuestiona quién controla realmente la narrativa.' WHERE slug='el-cine-cobra-vida';
UPDATE peliculas SET synopsis='Un viaje conceptual de veintisiete segundos por la estructura matemática subyacente al lenguaje humano, donde cada silencio es una variable y cada palabra una operación. Breve, preciso, inevitablemente correcto.' WHERE slug='el-lenguaje-es-matematico';
UPDATE peliculas SET synopsis='La tierra emite una señal dirigida a quienes saben escuchar. Un viajero recibe ese llamado y emprende un camino de transformación que lo lleva más lejos de lo que cualquier mapa podría indicar.' WHERE slug='el-llamado-de-la-tierra';
UPDATE peliculas SET synopsis='Una exploración animada del concepto de fe desde sus dimensiones religiosa, personal y cósmica. Un minuto y medio que pregunta en qué creemos cuando todo lo demás falla — y si eso que creemos nos salva o nos hunde.' WHERE slug='fe-faith';
UPDATE peliculas SET synopsis='En la superficie calma del agua florecen formas que no deberían existir. Una meditación visual sobre lo efímero, lo que no puede tocarse y la belleza que persiste precisamente porque no dura.' WHERE slug='flores-de-agua';
UPDATE peliculas SET synopsis='Un animatic que recorre el momento primigenio de la creación — no el bíblico, sino el personal. El instante en que el artista decide que algo que no existe debería existir y lo hace existir con las manos.' WHERE slug='genesis-animatic';
UPDATE peliculas SET synopsis='Un hijo navega la tensión irresuelta entre el mundo que lo formó y la naturaleza que siempre lo llamó. Seis minutos que exploran la identidad construida en la ausencia y lo que significa pertenecer a algo cuando nadie te lo enseñó.' WHERE slug='hijo-natural';
UPDATE peliculas SET synopsis='Un viaje sonoro y visual hacia una cosmología propia donde lo sagrado y lo cotidiano comparten el mismo espacio. Un corto que habla un idioma que no se aprende — se reconoce.' WHERE slug='huas-huas';
UPDATE peliculas SET synopsis='En el instante anterior al arrepentimiento existe una fracción de segundo donde el impulso toma el control. Este corto vive en ese instante y examina con honestidad lo que dejamos a su paso.' WHERE slug='impulso';
UPDATE peliculas SET synopsis='Kalle carga el peso de una sonrisa que ya no le pertenece. Un retrato animado de cuatro minutos sobre la fatiga emocional crónica, el esfuerzo invisible de parecer bien y lo que se rompe cuando nadie está mirando.' WHERE slug='kalle-sonrisa';
UPDATE peliculas SET synopsis='Un corto que juega con la ironía de su propio título: veintidós segundos que pretenden contener más de lo que cualquier historia larga podría. Lo consigue.' WHERE slug='la-historia-mas-larga';
UPDATE peliculas SET synopsis='Una tormenta que no es meteorológica — es existencial. En veinticinco segundos, la nieve cae sobre todo lo que creíamos saber sobre el calor humano y la voluntad de sobrevivir.' WHERE slug='la-nieve-que-mata';
UPDATE peliculas SET synopsis='Un experimento visual y sonoro que rechaza la narrativa lineal para construir algo más cercano a un estado mental que a una historia. Treinta y cinco segundos que se quedan más tiempo del que duran.' WHERE slug='laqu';
UPDATE peliculas SET synopsis='Luz y vida como conceptos que se persiguen mutuamente a lo largo de cinco minutos de animación. Un corto sobre la dependencia mutua entre lo que ilumina y lo que necesita ser iluminado para existir.' WHERE slug='light-life';
UPDATE peliculas SET synopsis='Dragocape evitó participar durante todo el año, hasta que la presión de último momento produjo exactamente esto. Una obra honesta sobre la procrastinación, el síndrome del impostor y lo que pasa cuando finalmente te rindes ante la fecha límite.' WHERE slug='me-hice-el-pendejo-todo-el-ano-y-no-iba-a-participar-pero-al-final-si-aso-que-hice-esta-mamada';
UPDATE peliculas SET synopsis='A medianoche, la ciudad pertenece a otros. Un personaje descubre qué — o quién — habita el espacio entre el último y el primer tren, en esa hora muerta que la mayoría duerme y una minoría nunca olvida.' WHERE slug='medianoche';
UPDATE peliculas SET synopsis='Una relación de poder examinada desde adentro: quién sirve, quién manda y si es posible distinguir uno del otro cuando la dinámica lleva suficiente tiempo instalada. Tres minutos que incomodan con precisión quirúrgica.' WHERE slug='mi-amo';
UPDATE peliculas SET synopsis='Una colección de micro-relatos oníricos que caben en un minuto y dejan la sensación de haber dormido horas. Fragmentos de inconsciente animado que dicen más en su brevedad que cualquier narración extensa.' WHERE slug='microsuenos';
UPDATE peliculas SET synopsis='Un juego que comenzó inocentemente se convierte en algo que ninguno de los participantes sabe cómo detener. Había reglas al principio. Luego solo quedó el impulso de seguir jugando aunque nadie recuerde por qué.' WHERE slug='no-debimos-jugar';
UPDATE peliculas SET synopsis='Un personaje acepta su suerte con una resignación que tiene algo de cómica y mucho de oscura. En su aceptación silenciosa se revela todo lo que decide soportar — y la pregunta de si realmente lo merece o solo lo cree.' WHERE slug='no-voy-a-decir-que-no-merezco-esto';
UPDATE peliculas SET synopsis='Los ojos ven — pero en este corto también son vistos. Una exploración de la mirada como espejo, como arma y como la única verdad que no podemos editar. Veintiocho segundos que no se olvidan fácilmente.' WHERE slug='ojos';
UPDATE peliculas SET synopsis='Una inmersión visual en los estados alterados que produce el opio — real, imaginario o metafórico. Un corto que explora el territorio de la percepción donde los límites entre lo que es y lo que se desea se disuelven.' WHERE slug='opium';
UPDATE peliculas SET synopsis='Una hija. Un padre. La distancia incómoda entre lo que uno quiso dar y lo que el otro aprendió a no pedir. Un corto sobre el silencio afectivo y lo que crece en él cuando nadie decide romperlo a tiempo.' WHERE slug='papa';
UPDATE peliculas SET synopsis='Cuando las calles se llenan de voces, cada protesta tiene un origen personal que las cámaras no capturan. Este corto cuenta una de esas historias — la que explica por qué alguien decide que callar ya no es una opción.' WHERE slug='protestas-una-historia';
UPDATE peliculas SET synopsis='Una pregunta que parece simple y una respuesta que tarda siete minutos en construirse. A través de distintas voces y formas, el corto desmonta la idea del héroe hasta sus componentes más básicos — y lo que queda es perturbador.' WHERE slug='que-es-un-heroe';
UPDATE peliculas SET synopsis='Entre la flor y la muerte hay un quizás. Entre el amor y la pérdida hay otro. Un poema visual que habita la incertidumbre como si fuera su hogar natural, con animación de Dulce Zavala que convierte lo indeciso en algo hermoso.' WHERE slug='quizas-la-flor-quizas-la-muerte-quizas';
UPDATE peliculas SET synopsis='Rojo y negro sobre blanco construyen un lenguaje visual que trasciende la representación para convertirse en emoción pura. Un corto que demuestra que la paleta más reducida puede contener el mayor universo.' WHERE slug='rojo-y-negro-sobre-blanco';
UPDATE peliculas SET synopsis='Dos hermanos con la misma sangre recorren rutas que se separan hasta que algo — inevitable, violento, necesario — los hace chocar de frente. Un corto sobre los vínculos que no elegimos y las consecuencias que sí.' WHERE slug='sangre-de-hermanos';
UPDATE peliculas SET synopsis='El corto más breve de la colección: cinco segundos para pronunciar la sílaba que lo cambia todo. Una obra minimalista que demuestra que el tiempo no determina el impacto.' WHERE slug='si';
UPDATE peliculas SET synopsis='Segunda entrega que amplía el universo visual de su predecesora con más brillo y más oscuridad en partes iguales. Una sonrisa que ya no sabemos si es de bienvenida o de advertencia.' WHERE slug='smile-shine-2';
UPDATE peliculas SET synopsis='Un trono que nadie ocupa y un poder que nadie reclama en voz alta. Cuatro minutos que exploran la autoridad vacía, lo que crece cuando nadie está mirando y la diferencia entre el símbolo y lo que representa.' WHERE slug='solio';
UPDATE peliculas SET synopsis='Un diamante flota entre estrellas en el espacio exterior — símbolo de valor absoluto en un entorno donde el valor no existe. Una aventura visual de tres minutos sobre la rareza, la belleza y las cosas que nadie puede reclamar.' WHERE slug='space-diamond';
UPDATE peliculas SET synopsis='El turismo espacial prometía ser el lujo definitivo del siglo XXI. Para un astronauta hambriento con un bot leal, resulta ser principalmente un problema de logística y depredadores. Una comedia de aventuras cósmica en un minuto.' WHERE slug='space-tourism';
UPDATE peliculas SET synopsis='Al final de la jornada, cuando el ruido cesa, quedan las preguntas que el movimiento constante no dejaba escuchar. Un minuto que examina qué queda de un día cuando por fin se acaba.' WHERE slug='terminado-el-dia';
UPDATE peliculas SET synopsis='Un partido que va mucho más allá del marcador — es el escenario donde se dirimen el orgullo, la identidad y la pertenencia. Todo lo que no puede medirse en goles se juega aquí con la misma intensidad.' WHERE slug='the-match';
UPDATE peliculas SET synopsis='El viaje final de un personaje que lo ha visto todo — desde el primer hasta el último tren, desde el principio hasta el acabamiento. Una historia sobre lo que decidimos llevar cuando ya no hay más destinos.' WHERE slug='trajecte-ultim';
UPDATE peliculas SET synopsis='Una ciudad hostil, gris y cansada tiene un habitante que no se entera de nada: un gato. El contraste entre la miseria del entorno y la indiferencia absoluta del felino es suficiente para verlo todo de otra manera.' WHERE slug='una-ciudad-de-mierda-con-un-gato';
UPDATE peliculas SET synopsis='La animación más breve de la colección: nueve segundos que contienen una ola, su núcleo y la energía que los conecta. Una demostración de que lo esencial no necesita más tiempo del que necesita para existir.' WHERE slug='wave-core';
